### ISSUE TITLE
gfx_backend_dx12 documenation failing to build on docs.rs

### ISSUE THREAD

**Issue by frankieD3** [gfx-rs/gfx#3320] opened 2020-07-28 00:32 UTC
Short info header:

- GFX version: All
- OS: N/A
- GPU: N/A

for a long while documentation for gfx_backend_dx12 is failing on docs.rs

**Comment by kvark** [comment] 2020-08-14 06:05
Dupe of #2957

**Closed by kvark** 2020-08-14 06:05 UTC
Labels: backend: DirectX-12, type: bug, value: medium
