### ISSUE TITLE
Expose debugging features in an implementation-agnostic manner?

### ISSUE THREAD

**Issue by AlphaModder** [gfx-rs/gfx#1508] opened 2017-09-20 05:27 UTC
The backends targeted by `gfx` all expose a number of debugging features to allow developers to more easily find and solve problems in their code. With the transition to a more low-level API, it may be appropriate to expose at least some of these features to developers in an implementation-agnostic manner where possible.

This topic has been brought up in a few issues before (#596, #1288, #1426), but these are old and did not have a full comparison between APIs, so in this one I have compiled a table of the available debugging features on each backend:

| debug feature | dx11 | dx12 | vulkan | metal | gl |
| ------------- | ---- | ---- | ------ | ----- | -- |
| Catching normally unchecked API misuse | **Yes**, via the debug layer enabled through [`D3D11_CREATE_DEVICE_FLAG::D3D11_CREATE_DEVICE_DEBUG`][1a]. Debug messages are accessible through [`ID3D11InfoQueue`][2a]. | **Yes**, via the debug layer enabled through a call to [`ID3D12Debug::EnableDebugLayer`][3a]. Debug messages are accessible through [`ID3D12InfoQueue`][4a]. | **Yes**, via the [validation layer mechanism][5a]. Debug messages are accessible to callbacks passed to `vkCreateDebugReportCallbackEXT`, exposed by the [`VK_EXT_debug_report`][6a] extension. | Set `METAL_DEVICE_WRAPPER_TYPE=1` environmental variable, see [This article][7a] on "Metal API Validation". | **Yes**, via the [`GL_KHR_debug`][8a] or [`GL_ARB_debug_output`][9a] extensions (identical interface). Enabled by setting the `GL_CONTEXT_FLAG_DEBUG_BIT` during context creation or calling `glEnable(GL_DEBUG_OUTPUT)`. Like Vulkan, messages are accessible through a callback mechanism. |
| Labelled resources | **Yes**, [`ID3D11DeviceChild::SetPrivateData`][1b] allows arbitrary data to be associated with a resource, and there is special support in the debug layer for named (ASCII-only, unfortunately) objects via a special GUID. | **Yes**, special support for names is provided by [`ID3D12Object::SetName`][2b], which supports Unicode. [`ID3D12Object::SetPrivateData`][3b] also exists. | **Yes**, objects may be assigned a name and color via the [`VK_EXT_debug_marker`][4b] extension. Requires [`VK_EXT_debug_report`][5a] to be enabled. | **Yes**, all [`MTLResource`s][5b] have an associated `label` property. | **Yes**, via the [`GL_KHR_debug`][8a] extension's `ObjectLabel` and `ObjectPtrLabel` functions. |
| Section/call marking | **Yes**, named markers and sections ('events') are supported via the [`ID3DUserDefinedAnnotation`][1c] interface. | **Yes**, via the [WinPixEventRuntime][2c], which supports named and colored markers and sections, as well as performance counters. | **Yes**, named and colored markers and sections are also supported via the [`VK_EXT_debug_marker`][4b] extension. | **Yes**, named sections and markers, are supported via the `insertDebugSignpost`, `pushDebugGroup`, and `popDebugGroup` methods of [`MTLCommandEncoder`][3c] GPU commands can also be captured within labeled regions with [Metal GPU Capture][4c]. | **Yes**, the [`GL_KHR_debug`][8a] extension also supports named sections (but not individual markers) via the `PushDebugGroup` and `PopDebugGroup` functions.
| Other features | Shader execution tracking via the [`ID3D11TracingDevice`][1d] interface when the debug layer is enabled. | Checking resource states with [`ID3D12DebugCommandList::AssertResourceState`][2d] and [`ID3D12DebugCommandQueue::AssertResourceState`][3d], querying live objects with [`ID3D12DebugDevice::ReportLiveDeviceObjects`][4d], gpu-level shader validation via a call to [`ID3D12Debug1::SetEnableGPUBasedValidation`][5d] when the debug layer is enabled. (experimental, only on Win10 Anniversary Update) | Periodic screenshots with `VK_LAYER_LUNARG_screenshot`, Write API calls to file with `VK_LAYER_LUNARG_api_dump`, FPS counter in titlebar with `VK_LAYER_LUNARG_monitor` | None? | None?

Aside from the extra features, it seems that the APIs' debugging features are roughly on-par with eachother. One thing that I anticipate might be an issue would be finding a consistent way to map labels on gfx objects to labels to each implementation's internal resources. Another question would be if we want to attempt to emulate colored labels on GL, Metal, and DX11. 

I am still rather inexperienced with graphics programming, so let me know if anything on the table is missing or incorrect. 

[1a]: https://msdn.microsoft.com/en-us/library/windows/desktop/hh446868(v=vs.85).aspx
[2a]: https://msdn.microsoft.com/en-us/library/windows/desktop/ff476538(v=vs.85).aspx
[3a]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn986877(v=vs.85).aspx
[4a]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn950163(v=vs.85).aspx
[5a]: https://vulkan.lunarg.com/doc/sdk/1.0.61.0/windows/layers.html
[6a]: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_debug_report
[7a]: https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Dev-Technique/Dev-Technique.html
[8a]: https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt
[9a]: https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_debug_output.txt
[1b]: https://msdn.microsoft.com/en-us/library/windows/desktop/ff476383(v=vs.85).aspx
[2b]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn788701(v=vs.85).aspx
[3b]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn788702(v=vs.85).aspx
[4b]: https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VK_EXT_debug_marker
[5b]: https://developer.apple.com/documentation/metal/mtlresource
[1c]: https://msdn.microsoft.com/en-us/library/windows/desktop/hh446881(v=vs.85).aspx
[2c]: https://blogs.msdn.microsoft.com/pix/winpixeventruntime/
[3c]: https://developer.apple.com/documentation/metal/mtlcommandencoder
[4c]: https://developer.apple.com/documentation/metal/tools_profiling_and_debugging/metal_gpu_capture
[1d]: https://msdn.microsoft.com/en-us/library/windows/desktop/hh446868(v=vs.85).aspx
[2d]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn950155(v=vs.85).aspx
[3d]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn950158(v=vs.85).aspx
[4d]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn986875(v=vs.85).aspx
[5d]: https://msdn.microsoft.com/en-us/library/windows/desktop/mt762995(v=vs.85).aspx

**Comment by kvark** [comment] 2017-09-20 09:02
Wow, that is lovely 👍 
> This topic has been brought up in a few issues before (#596, #1288, #1426), but these are old and ...

To be fair, #1426 isn't that old :) Also, there is https://github.com/gfx-rs/gfx/issues/1288 which is on the way of being a duplicate of this one.

> Unknown. This article mentions "Metal API Validation", but I cannot find any other information.

@JohnColanduoni pointed out earlier (on IRC) to use `METAL_DEVICE_WRAPPER_TYPE=1` environmental variable. Frankly, I wish all debugging in all APIs could be done this way, to avoid code changes (even if controlled by the runtime).

**Comment by snuk182** [comment] 2018-04-10 07:56
[METAL_DEVICE_WRAPPER_TYPE=1](https://twitter.com/icculus/status/755453525040230401) ?

**Comment by kvark** [comment] 2020-03-20 21:15
I'm working on the debug markers in the command stream.

**Comment by kvark** [comment] 2020-03-22 23:57
I think this is *mostly* addressed now:

- [x] Catching normally unchecked API misuse

Vulkan, OpenGL, and DX* enable the layers by default in debug. Metal - we can't do this, since validation panics.

- [x] Labelled resources

Fixed in #3000

- [x] Section/call marking

Fixed in #3169

- [ ] Other features

Looks like we'll be able to follow-up with this with either platform-specific APIs or just internal changes to the backends.

**Closed by kvark** 2020-03-22 23:57 UTC
Labels: difficulty: average, module: hal, status: ready for work, type: feature, value: high
