### ISSUE TITLE
GL backend shading_language parsing fails

### ISSUE THREAD

**Issue by PvdBerg1998** [gfx-rs/gfx#1629] opened 2017-11-15 10:08 UTC
https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/info.rs line 193 fails on some systems, `gl.GetString` returns a null pointer. Can I quickfix this? It prevents my application from working on most systems since it panics.

**EDIT: This only happens on Win10, not on a linux virtualbox**

**Comment by msiglreith** [comment] 2017-11-15 11:00
Could you print the returned version information from the GL (before parse)?

**Comment by PvdBerg1998** [comment] 2017-11-16 12:32
For some reason Visual Studio Code and Visual Studio 2017 are unable to debug the executable anymore, I don't know what's wrong. I will try to clone and edit gfx's source.

**Comment by PvdBerg1998** [comment] 2017-11-16 19:19
I can't use my edited dependency, see my reddit post: https://www.reddit.com/r/rust/comments/7dci9i/dependency_patching_error/

**Comment by msiglreith** [comment] 2017-11-16 20:12
Have you used the `0.16` or `pre-ll` branch?
Nonetheless, locally cloning and running the triangle example (of one of the mentioned branches) should work also.

**Comment by PvdBerg1998** [comment] 2017-11-16 20:59
How do I run that? Following the instructions does not work

**Comment by PvdBerg1998** [comment] 2017-11-16 21:26
@msiglreith Maybe you can build a test for me?

**Comment by msiglreith** [comment] 2017-11-16 22:01
@PvdBerg1998 
I setup a branch here: https://github.com/msiglreith/gfx/tree/gl-version
Running `cargo run --example triangle` in the root directory should work. The console will print out two strings, GL version and GLSL version.
Example output from my system:
```
"4.5.13492 Compatibility Profile/Debug Context 22.19.677.257"
"4.50"
```

**Comment by PvdBerg1998** [comment] 2017-11-17 12:52
@msiglreith Runs on my Win10 desktop (the machine where the bug does not occur). Output: 
```
"4.5.0 NVIDIA 384.94"
"4.50 NVIDIA"
```

Also runs on the laptop where the crash occurs:
```
"4.4.0 - Build 21.20.16.4574"
"4.40 - Build 21.20.16.4574"
```
So the `get_version` function does not return null here?

**Comment by msiglreith** [comment] 2017-11-17 13:09
Ok, thanks for the output. If I understand it correctly, the triangle example works fine even on the laptop, but it crashes in your application? Could you provide a minimal example for reproducing or give us access to the source? Might be an error on context creation earlier.

**Comment by PvdBerg1998** [comment] 2017-11-17 13:13
Yes, I have been trying to patch the dependency to use your branch just now. Having some trouble though.
The error occurs when using the Piston library. You can use their hello world example: https://github.com/PistonDevelopers/piston_window

**Comment by PvdBerg1998** [comment] 2017-11-17 13:14
I had also created an issue for piston: https://github.com/PistonDevelopers/piston/issues/1214

**Comment by McGittyHub** [comment] 2017-11-22 08:15
I'm experiencing the same issue after updating rust and _only_ when running `cargo run --release`

Version: `rustc 1.23.0-nightly (63739ab7b 2017-11-21)`

**Comment by msiglreith** [comment] 2017-11-22 13:03
@McGittyHub Thanks for the report, I'm able to reproduce it locally but not sure what's causing the issue, might be a nightly regression. It also fails when running our triangle example in release mode.
It seems to fail loading the GL1.1 functions correctly for me, which includes `gl.GetString`.

**Comment by msiglreith** [comment] 2017-11-22 14:37
Looks like a nightly regression: https://github.com/rust-lang/rust/issues/46182

**Comment by msiglreith** [comment] 2017-11-22 15:57
Update: The issue is due to the `PROC` definition in gl-rs, which is marked as non-null by the compiler in release due to the `"system"` ABI, boiling down to missing `kernel32::GetProcAddress` call and getting null-ptrs for the OpenGL 1.1 functions.

The mentioned typedef must be fixed in gl-rs, glutin needs to be updated to the new gl-rs version and gfx-rs must also update to the new glutin version then, yay.

**Comment by anderejd** [comment] 2017-11-22 16:43
@msiglreith I'm curious about your post in the rust repos issue, I did not quite get the explanation. Did the null check get optimized away in release mode?
```        
if !p.is_null() {
    panic!("{:?}", p);
    return p;
}
```

Or was something else?

**Comment by PvdBerg1998** [comment] 2019-03-09 21:13
It's been a while. I checked out the linked glrs issue and it seems to be fixed. This issue is probably unblocked?

**Comment by msiglreith** [comment] 2019-03-09 22:21
yes, thanks!

**Closed by msiglreith** 2019-03-09 22:21 UTC
Labels: backend: OpenGL, status: blocked, type: bug, value: high
